[package]
name = "cargo-miri-test"
version = "0.1.0"
authors = ["Miri Team"]
edition = "2018"

[dependencies]
the_macro = { path = "proc-macro" }

[build-dependencies]
autocfg = "1"

[lib]
test = false # test that this is respected (will show in the output)

[[test]]
name = "main"
harness = false
